"""Build the 4 lab notebooks for Fundamentals of NLP.

Run from the Notebooks/ folder:
    python _build_notebooks.py
"""
import json
import os
from pathlib import Path

HERE = Path(__file__).parent


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": "\n".join(lines),
    }


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": "\n".join(lines),
    }


def notebook(cells: list) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write(name: str, cells: list) -> None:
    nb = notebook(cells)
    out = HERE / name
    with out.open("w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"  wrote {out.name} ({len(cells)} cells)")


# ---------------------------------------------------------------------------
# Lab 01 — Tokenization
# ---------------------------------------------------------------------------

lab01 = [
    md(
        "# Lab 01 — Tokenization",
        "",
        "**Course:** Fundamentals of NLP",
        "**Audience:** M1 GAMMA, L2 LMAD Data Science",
        "**Author:** Aymen Ben Brik",
        "",
        "## Objectives",
        "",
        "By the end of this lab, you will be able to:",
        "1. Tokenize text at three granularities (word, character, sub-word).",
        "2. Compare the trade-offs between vocabulary size, sequence length, and OOV rate.",
        "3. Implement the Byte-Pair Encoding (BPE) algorithm from scratch.",
        "4. Use modern pre-trained tokenizers (BERT, GPT-2) and inspect their behaviour.",
        "5. Discuss multilingual and dialectal tokenization challenges.",
        "",
        "## Prerequisites",
        "",
        "```bash",
        "pip install nltk transformers regex",
        "```",
    ),
    md("## 1. Setup"),
    code(
        "import re",
        "from collections import Counter, defaultdict",
        "import nltk",
        "for pkg in ('punkt', 'punkt_tab'):",
        "    try:",
        "        nltk.download(pkg, quiet=True)",
        "    except Exception:",
        "        pass",
    ),
    md(
        "## 2. Whitespace tokenization",
        "",
        "The simplest tokenizer just splits on whitespace. Try it on a few sentences and notice the limitations: punctuation glued to words, contractions kept together, multiple spaces preserved.",
    ),
    code(
        "text = \"I've been to Sfax-University; it's amazing! See you tomorrow.\"",
        "tokens = text.split()",
        "print('Whitespace tokens:', tokens)",
        "print('Number of tokens:', len(tokens))",
    ),
    md("## 3. Whitespace + punctuation (regex)"),
    code(
        "tokens = re.findall(r\"\\w+|[^\\w\\s]\", text)",
        "print('Regex tokens:', tokens)",
        "print('Number of tokens:', len(tokens))",
    ),
    md(
        "**Question.** What happens to *I've*? What happens to *Sfax-University*? Comment.",
    ),
    md("## 4. NLTK word tokenizer"),
    code(
        "tokens = nltk.word_tokenize(text)",
        "print('NLTK tokens:', tokens)",
        "print('Number of tokens:', len(tokens))",
    ),
    md(
        "Notice that NLTK splits *I've* into *I* + *'ve*, and treats *Sfax-University* differently from a regex split.",
    ),
    md("## 5. Character-level tokenization"),
    code(
        "char_tokens = list(text)",
        "print('First 30 chars:', char_tokens[:30])",
        "print('Vocabulary size (unique chars):', len(set(char_tokens)))",
        "print('Sequence length:', len(char_tokens))",
    ),
    md(
        "**Trade-off observed.** The vocabulary is tiny (a few dozen distinct characters), but sequence length is much longer than at the word level. Models pay a memory and compute cost for character-level inputs.",
    ),
    md(
        "## 6. Byte-Pair Encoding from scratch",
        "",
        "We implement BPE on a small corpus and watch the merges grow.",
    ),
    code(
        "def get_pair_counts(vocab: dict) -> Counter:",
        "    pairs = Counter()",
        "    for word, freq in vocab.items():",
        "        symbols = word.split()",
        "        for i in range(len(symbols) - 1):",
        "            pairs[(symbols[i], symbols[i + 1])] += freq",
        "    return pairs",
        "",
        "def merge_vocab(pair: tuple, vocab: dict) -> dict:",
        "    bigram = re.escape(' '.join(pair))",
        "    pattern = re.compile(r'(?<!\\S)' + bigram + r'(?!\\S)')",
        "    new_vocab = {}",
        "    for word, freq in vocab.items():",
        "        new_word = pattern.sub(''.join(pair), word)",
        "        new_vocab[new_word] = freq",
        "    return new_vocab",
        "",
        "def train_bpe(corpus_words: dict, num_merges: int) -> tuple:",
        "    \"\"\"Each key is a word represented as space-separated chars + </w>.\"\"\"",
        "    vocab = {' '.join(list(w)) + ' </w>': f for w, f in corpus_words.items()}",
        "    merges = []",
        "    for step in range(num_merges):",
        "        pairs = get_pair_counts(vocab)",
        "        if not pairs:",
        "            break",
        "        best = pairs.most_common(1)[0][0]",
        "        merges.append(best)",
        "        vocab = merge_vocab(best, vocab)",
        "        print(f'Step {step + 1}: merge {best} (freq {pairs[best]})')",
        "    return vocab, merges",
        "",
        "corpus = {'low': 5, 'lower': 2, 'newest': 6, 'widest': 3}",
        "vocab, merges = train_bpe(corpus, num_merges=10)",
        "",
        "print('\\nFinal vocabulary entries:')",
        "for w, f in vocab.items():",
        "    print(f'  {w:<20} freq={f}')",
    ),
    md(
        "**Observation.** Frequent words (`low`, `newest`) are merged into single tokens. Rare combinations remain decomposed. The merge order is the BPE *training output*, used at inference to tokenize new words.",
    ),
    md("## 7. Pre-trained tokenizers (BERT vs GPT-2)"),
    code(
        "# pip install transformers if needed",
        "try:",
        "    from transformers import AutoTokenizer",
        "    bert = AutoTokenizer.from_pretrained('bert-base-uncased')",
        "    gpt2 = AutoTokenizer.from_pretrained('gpt2')",
        "    sentence = \"Tokenization underlies every NLP system.\"",
        "    print('BERT tokens:', bert.tokenize(sentence))",
        "    print('GPT-2 tokens:', gpt2.tokenize(sentence))",
        "except ImportError:",
        "    print('Install transformers: pip install transformers')",
    ),
    md(
        "**Discussion.**",
        "- BERT uses *WordPiece*, marking sub-word continuations with `##`.",
        "- GPT-2 uses byte-level BPE, with leading-space markers (`Ġ`).",
        "Both produce different sub-word splits despite the same algorithmic family.",
    ),
    md("## 8. Multilingual / dialectal challenge"),
    code(
        "dialectal = \"n7eb el sufflé bil chocolat n3awd l week-end jay\"  # Tunisian arabizi + French",
        "try:",
        "    print('BERT (English):', bert.tokenize(dialectal))",
        "    multi = AutoTokenizer.from_pretrained('xlm-roberta-base')",
        "    print('XLM-R (multilingual):', multi.tokenize(dialectal))",
        "except (NameError, OSError):",
        "    print('Skipping (transformers / model not available)')",
    ),
    md(
        "**Observation.** A general English tokenizer fragments dialectal arabizi badly (digits like `7` become rare sub-tokens). A multilingual tokenizer like XLM-R does noticeably better.",
    ),
    md(
        "## Exercises",
        "",
        "**Exercise 1.** Tokenize the sentence \"*The CEOs' meeting was rescheduled.*\" with three different tokenizers (regex, NLTK, BERT). Comment on the differences for the words *CEOs'* and *rescheduled*.",
        "",
        "**Exercise 2.** Train BPE on the toy corpus `{'xay': 1, 'yax': 1, 'xy': 1}` for 4 merges. List the new vocabulary at each step.",
        "",
        "**Exercise 3.** For the GPT-2 tokenizer, count how many tokens the following English-vs-French sentence pair produces. Comment on cross-lingual fairness:",
        "- *\"The weather is nice today.\"*",
        "- *\"Le temps est agréable aujourd'hui.\"*",
        "",
        "**Exercise 4.** Pick a Tunisian dialectal sentence of your own. Tokenize it with three different tokenizers and identify the strengths and weaknesses of each.",
        "",
        "**Exercise 5 (synthesis).** Implement the *encoding* phase of BPE: given a list of merges learnt from a corpus, write a function that tokenizes a new (unseen) word by greedily applying the merges in order.",
    ),
]

# ---------------------------------------------------------------------------
# Lab 02 — Bag-of-Words and TF-IDF classifier
# ---------------------------------------------------------------------------

lab02 = [
    md(
        "# Lab 02 — Bag-of-Words, TF-IDF and a text classifier",
        "",
        "**Course:** Fundamentals of NLP",
        "**Author:** Aymen Ben Brik",
        "",
        "## Objectives",
        "",
        "1. Build a Bag-of-Words document-term matrix from scratch.",
        "2. Compute TF-IDF weights and contrast them with raw counts.",
        "3. Train a logistic-regression text classifier on TF-IDF features.",
        "4. Inspect the most discriminative features per class.",
        "5. Compare classifier performance against a Naive Bayes baseline.",
        "",
        "## Prerequisites",
        "",
        "```bash",
        "pip install scikit-learn matplotlib",
        "```",
    ),
    md("## 1. Setup and dataset"),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "from collections import Counter",
        "from sklearn.datasets import fetch_20newsgroups",
        "from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer",
        "from sklearn.linear_model import LogisticRegression",
        "from sklearn.naive_bayes import MultinomialNB",
        "from sklearn.metrics import classification_report, confusion_matrix",
        "from sklearn.model_selection import train_test_split",
        "",
        "# 4 well-separated newsgroup categories",
        "categories = ['rec.sport.hockey', 'sci.space', 'comp.graphics', 'talk.politics.misc']",
        "data = fetch_20newsgroups(subset='all', categories=categories,",
        "                           remove=('headers', 'footers', 'quotes'))",
        "print(f'Number of documents: {len(data.data)}')",
        "print(f'Categories: {data.target_names}')",
        "print(f'\\nExample (label = {data.target_names[data.target[0]]}):')",
        "print(data.data[0][:300], '...')",
    ),
    md("## 2. Bag-of-Words from scratch"),
    code(
        "def bow_from_scratch(corpus, vocab=None):",
        "    \"\"\"Returns (matrix, vocab) where matrix[i, j] = count of vocab[j] in corpus[i].\"\"\"",
        "    tokenized = [doc.lower().split() for doc in corpus]",
        "    if vocab is None:",
        "        all_words = sorted({w for doc in tokenized for w in doc})",
        "        vocab = {w: j for j, w in enumerate(all_words)}",
        "    matrix = np.zeros((len(corpus), len(vocab)), dtype=int)",
        "    for i, doc in enumerate(tokenized):",
        "        counts = Counter(doc)",
        "        for w, c in counts.items():",
        "            if w in vocab:",
        "                matrix[i, vocab[w]] = c",
        "    return matrix, vocab",
        "",
        "small_corpus = [",
        "    'the room was clean and quiet',",
        "    'the breakfast was great and the room was clean',",
        "    'service was slow but rooms were clean',",
        "]",
        "M, V = bow_from_scratch(small_corpus)",
        "print('Vocabulary size:', len(V))",
        "print('Matrix shape:', M.shape)",
        "print('Document-term matrix:')",
        "print(M)",
    ),
    md("## 3. CountVectorizer (sklearn equivalent)"),
    code(
        "cv = CountVectorizer().fit(small_corpus)",
        "X = cv.transform(small_corpus).toarray()",
        "print('sklearn vocabulary:', cv.get_feature_names_out())",
        "print('sklearn matrix:')",
        "print(X)",
    ),
    md("## 4. TF-IDF: from raw counts to weighted features"),
    code(
        "tfidf = TfidfVectorizer().fit(small_corpus)",
        "X_tfidf = tfidf.transform(small_corpus).toarray().round(3)",
        "print('Vocabulary:', tfidf.get_feature_names_out())",
        "print('TF-IDF matrix:')",
        "print(X_tfidf)",
        "",
        "print('\\nIDF of each word:')",
        "for word, idf in zip(tfidf.get_feature_names_out(), tfidf.idf_):",
        "    print(f'  {word:<12} IDF = {idf:.3f}')",
    ),
    md(
        "**Observation.** Words appearing in every document (`the`, `was`) get the lowest IDF and contribute little to the representation. Discriminative words (`breakfast`, `service`, `slow`) get high IDF and dominate.",
    ),
    md("## 5. Train a TF-IDF + Logistic Regression classifier on 20 Newsgroups"),
    code(
        "X_train, X_test, y_train, y_test = train_test_split(",
        "    data.data, data.target, test_size=0.2, random_state=42, stratify=data.target,",
        ")",
        "",
        "vectorizer = TfidfVectorizer(min_df=5, max_df=0.7, stop_words='english', ngram_range=(1, 2))",
        "Xtr = vectorizer.fit_transform(X_train)",
        "Xte = vectorizer.transform(X_test)",
        "print(f'Train shape: {Xtr.shape}, Test shape: {Xte.shape}')",
        "",
        "clf = LogisticRegression(max_iter=2000, C=1.0)",
        "clf.fit(Xtr, y_train)",
        "y_pred = clf.predict(Xte)",
        "print(classification_report(y_test, y_pred, target_names=data.target_names))",
    ),
    md("## 6. Confusion matrix"),
    code(
        "cm = confusion_matrix(y_test, y_pred)",
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "im = ax.imshow(cm, cmap='Blues')",
        "ax.set_xticks(range(4)); ax.set_yticks(range(4))",
        "ax.set_xticklabels(data.target_names, rotation=30, ha='right')",
        "ax.set_yticklabels(data.target_names)",
        "for i in range(4):",
        "    for j in range(4):",
        "        ax.text(j, i, cm[i, j], ha='center', va='center', color='black' if cm[i, j] < cm.max()/2 else 'white')",
        "ax.set_xlabel('Predicted'); ax.set_ylabel('True')",
        "ax.set_title('Confusion matrix')",
        "fig.colorbar(im); plt.tight_layout()",
        "plt.show()",
    ),
    md("## 7. Most discriminative features per class"),
    code(
        "feature_names = vectorizer.get_feature_names_out()",
        "for class_idx, class_name in enumerate(data.target_names):",
        "    top = np.argsort(clf.coef_[class_idx])[-10:][::-1]",
        "    words = [feature_names[i] for i in top]",
        "    print(f'\\n{class_name}: {words}')",
    ),
    md("## 8. Naive Bayes baseline"),
    code(
        "nb = MultinomialNB().fit(Xtr, y_train)",
        "y_pred_nb = nb.predict(Xte)",
        "print(classification_report(y_test, y_pred_nb, target_names=data.target_names))",
    ),
    md(
        "**Comparison.** Naive Bayes is faster but typically a few F1 points behind logistic regression on TF-IDF features. Both are strong, fast baselines that should be tried before any deep model.",
    ),
    md(
        "## Exercises",
        "",
        "**Exercise 1.** Re-train the classifier without `stop_words='english'`. Does accuracy go up or down? Inspect the most discriminative words: do you see stop words appearing? Why or why not?",
        "",
        "**Exercise 2.** Compute the TF-IDF representation by hand for the corpus:",
        "- *d1: 'NLP is fun and useful'*",
        "- *d2: 'Tunisia is a country in North Africa'*",
        "- *d3: 'NLP is widely used in Tunisia'*",
        "",
        "**Exercise 3.** Try `ngram_range=(1, 3)` and report the change in F1. What is the cost (vocabulary size, training time)?",
        "",
        "**Exercise 4.** The classifier confuses some categories more than others. Identify the two most-confused classes from the confusion matrix and propose a hypothesis for why.",
        "",
        "**Exercise 5 (synthesis).** Replace the categories with `['talk.politics.misc', 'talk.politics.guns', 'talk.politics.mideast']` (more semantically related). Does accuracy drop? Explain in terms of the limitations of bag-of-words.",
    ),
]

# ---------------------------------------------------------------------------
# Lab 03 — Word2Vec embeddings
# ---------------------------------------------------------------------------

lab03 = [
    md(
        "# Lab 03 — Word2Vec and word embeddings",
        "",
        "**Course:** Fundamentals of NLP",
        "**Author:** Aymen Ben Brik",
        "",
        "## Objectives",
        "",
        "1. Train a Word2Vec model on a real corpus and inspect the resulting vectors.",
        "2. Explore semantic similarity, nearest neighbours, and word analogies.",
        "3. Visualize embeddings in 2D using PCA.",
        "4. Contrast skip-gram and CBOW.",
        "5. Identify limitations: out-of-vocabulary words, polysemy, biases.",
        "",
        "## Prerequisites",
        "",
        "```bash",
        "pip install gensim nltk scikit-learn matplotlib",
        "```",
    ),
    md("## 1. Setup and corpus"),
    code(
        "import nltk",
        "for pkg in ('brown', 'punkt', 'punkt_tab'):",
        "    try:",
        "        nltk.download(pkg, quiet=True)",
        "    except Exception:",
        "        pass",
        "from nltk.corpus import brown",
        "from gensim.models import Word2Vec",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "from sklearn.decomposition import PCA",
        "",
        "# Brown corpus: ~1M tokens of American English from the 1960s",
        "sentences = [[w.lower() for w in s] for s in brown.sents()]",
        "print(f'Number of sentences: {len(sentences)}')",
        "print(f'First sentence: {sentences[0][:15]} ...')",
    ),
    md("## 2. Train Word2Vec (skip-gram)"),
    code(
        "model_sg = Word2Vec(",
        "    sentences=sentences,",
        "    vector_size=100,",
        "    window=5,",
        "    min_count=5,",
        "    sg=1,            # skip-gram",
        "    negative=5,",
        "    epochs=5,",
        "    workers=4,",
        "    seed=42,",
        ")",
        "print(f'Vocabulary size: {len(model_sg.wv)}')",
        "print(f'Vector dimension: {model_sg.wv.vector_size}')",
    ),
    md("## 3. Word similarity"),
    code(
        "words = ['king', 'queen', 'computer', 'paris', 'love', 'war']",
        "for w in words:",
        "    if w in model_sg.wv:",
        "        sims = model_sg.wv.most_similar(w, topn=5)",
        "        print(f'\\nMost similar to \"{w}\":')",
        "        for sw, s in sims:",
        "            print(f'  {sw:<15} {s:.3f}')",
        "    else:",
        "        print(f'{w} not in vocabulary')",
    ),
    md("## 4. Word analogies"),
    code(
        "def analogy(model, a, b, c):",
        "    \"\"\"a is to b as c is to ?\"\"\"",
        "    try:",
        "        return model.wv.most_similar(positive=[b, c], negative=[a], topn=3)",
        "    except KeyError as e:",
        "        return f'Missing word: {e}'",
        "",
        "tests = [",
        "    ('man', 'king', 'woman'),    # king -> queen?",
        "    ('paris', 'france', 'london'),  # london -> england?",
        "    ('walk', 'walking', 'run'),  # run -> running?",
        "]",
        "for a, b, c in tests:",
        "    print(f'{a}:{b} :: {c}:?')",
        "    print(f'  {analogy(model_sg, a, b, c)}')",
    ),
    md(
        "**Note.** A small corpus (1M tokens) yields imperfect analogies. Production-quality vectors are trained on hundreds of billions of tokens.",
    ),
    md("## 5. Visualize embeddings (PCA)"),
    code(
        "selected = ['king', 'queen', 'man', 'woman', 'paris', 'london', 'tokyo', 'france',",
        "            'england', 'japan', 'apple', 'orange', 'banana', 'computer', 'car', 'truck']",
        "selected = [w for w in selected if w in model_sg.wv]",
        "vectors = np.array([model_sg.wv[w] for w in selected])",
        "vectors_2d = PCA(n_components=2).fit_transform(vectors)",
        "",
        "plt.figure(figsize=(8, 6))",
        "plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1])",
        "for w, (x, y) in zip(selected, vectors_2d):",
        "    plt.annotate(w, (x, y), fontsize=10)",
        "plt.title('Word embeddings projected to 2D (PCA)')",
        "plt.xlabel('PC 1'); plt.ylabel('PC 2')",
        "plt.grid(alpha=0.3); plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "**Observation.** Geographic words tend to cluster together; royal terms cluster; food terms form their own group. The 100-dim space encodes coarse semantic structure even from a small training corpus.",
    ),
    md("## 6. Skip-gram vs CBOW"),
    code(
        "model_cbow = Word2Vec(",
        "    sentences=sentences,",
        "    vector_size=100, window=5, min_count=5,",
        "    sg=0,            # CBOW",
        "    negative=5, epochs=5, workers=4, seed=42,",
        ")",
        "",
        "for w in ['king', 'computer', 'love']:",
        "    print(f'\\n--- {w} ---')",
        "    if w in model_sg.wv:",
        "        print('Skip-gram:', [s[0] for s in model_sg.wv.most_similar(w, topn=5)])",
        "    if w in model_cbow.wv:",
        "        print('CBOW    :', [s[0] for s in model_cbow.wv.most_similar(w, topn=5)])",
    ),
    md(
        "**Discussion.** Skip-gram and CBOW often produce qualitatively different neighbours. Skip-gram tends to be better on rare words; CBOW is faster to train and often better on frequent words.",
    ),
    md("## 7. Limitations: OOV and polysemy"),
    code(
        "# OOV: a word that does not appear at least 5 times in the corpus",
        "for w in ['javascript', 'tunisia', 'transformer']:",
        "    print(f'  {w!r} in vocabulary: {w in model_sg.wv}')",
        "",
        "# Polysemy: \"bank\" has only one vector",
        "if 'bank' in model_sg.wv:",
        "    print(\"\\nMost similar to 'bank' (mixes financial AND river senses):\")",
        "    for w, s in model_sg.wv.most_similar('bank', topn=10):",
        "        print(f'  {w:<15} {s:.3f}')",
    ),
    md(
        "## Exercises",
        "",
        "**Exercise 1.** Train Word2Vec with `vector_size=300` instead of 100. Do nearest neighbours improve?",
        "",
        "**Exercise 2.** Create three analogy tests of your own (geographic, syntactic, social) and report the results. Discuss which fail and why.",
        "",
        "**Exercise 3.** Replace Word2Vec by FastText (`from gensim.models import FastText`). Show that FastText handles OOV words by computing a vector for an unseen word.",
        "",
        "**Exercise 4.** Compute the cosine similarity between `'man'` and `'doctor'`, and between `'woman'` and `'doctor'`. Repeat with `'nurse'`. Comment on potential gender bias.",
        "",
        "**Exercise 5 (synthesis).** Train Word2Vec on a domain-specific corpus of your choice (e.g., a Wikipedia dump in French, or the NLTK Gutenberg corpus). Compare nearest neighbours of a polysemous word (e.g., *bank*, *bat*, *crane*) with those obtained from the Brown corpus. What does the comparison tell you about the data-dependence of embeddings?",
    ),
]

# ---------------------------------------------------------------------------
# Lab 04 — Evaluation metrics
# ---------------------------------------------------------------------------

lab04 = [
    md(
        "# Lab 04 — Evaluation metrics",
        "",
        "**Course:** Fundamentals of NLP",
        "**Author:** Aymen Ben Brik",
        "",
        "## Objectives",
        "",
        "1. Build a confusion matrix and compute Accuracy, Precision, Recall, F1 from scratch.",
        "2. Demonstrate the class-imbalance pitfall of accuracy.",
        "3. Plot ROC and Precision-Recall curves.",
        "4. Implement Perplexity for a small language model.",
        "5. Implement BLEU and ROUGE on translation/summary pairs.",
        "",
        "## Prerequisites",
        "",
        "```bash",
        "pip install scikit-learn matplotlib nltk rouge-score",
        "```",
    ),
    md("## 1. Setup"),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "from sklearn.datasets import fetch_20newsgroups",
        "from sklearn.feature_extraction.text import TfidfVectorizer",
        "from sklearn.linear_model import LogisticRegression",
        "from sklearn.model_selection import train_test_split",
        "from sklearn.metrics import (classification_report, confusion_matrix,",
        "                             precision_recall_fscore_support, roc_curve, auc,",
        "                             precision_recall_curve, average_precision_score)",
    ),
    md("## 2. Build a binary classifier (sci.space vs comp.graphics)"),
    code(
        "categories = ['sci.space', 'comp.graphics']",
        "data = fetch_20newsgroups(subset='all', categories=categories,",
        "                           remove=('headers', 'footers', 'quotes'))",
        "X_train, X_test, y_train, y_test = train_test_split(",
        "    data.data, data.target, test_size=0.25, random_state=42, stratify=data.target,",
        ")",
        "vec = TfidfVectorizer(min_df=5, max_df=0.7, stop_words='english')",
        "Xtr, Xte = vec.fit_transform(X_train), vec.transform(X_test)",
        "clf = LogisticRegression(max_iter=2000).fit(Xtr, y_train)",
        "y_pred = clf.predict(Xte)",
        "y_score = clf.predict_proba(Xte)[:, 1]   # probability of class 1",
    ),
    md("## 3. Confusion matrix and metrics from scratch"),
    code(
        "def metrics_from_scratch(y_true, y_pred):",
        "    TP = int(np.sum((y_true == 1) & (y_pred == 1)))",
        "    FP = int(np.sum((y_true == 0) & (y_pred == 1)))",
        "    FN = int(np.sum((y_true == 1) & (y_pred == 0)))",
        "    TN = int(np.sum((y_true == 0) & (y_pred == 0)))",
        "    accuracy  = (TP + TN) / (TP + TN + FP + FN)",
        "    precision = TP / (TP + FP) if (TP + FP) else 0.0",
        "    recall    = TP / (TP + FN) if (TP + FN) else 0.0",
        "    f1        = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0",
        "    return dict(TP=TP, FP=FP, FN=FN, TN=TN,",
        "                Accuracy=accuracy, Precision=precision, Recall=recall, F1=f1)",
        "",
        "scratch = metrics_from_scratch(np.asarray(y_test), np.asarray(y_pred))",
        "for k, v in scratch.items():",
        "    print(f'  {k:<10} = {v:.3f}' if isinstance(v, float) else f'  {k:<10} = {v}')",
    ),
    md("## 4. Compare with sklearn"),
    code(
        "print(classification_report(y_test, y_pred, target_names=categories, digits=3))",
    ),
    md("## 5. Class-imbalance pitfall"),
    code(
        "# Build an artificial imbalanced test where 95% of inputs are class 0",
        "rng = np.random.default_rng(42)",
        "idx_pos = np.where(y_test == 1)[0]; idx_neg = np.where(y_test == 0)[0]",
        "n_pos = max(1, len(idx_pos) // 10)",
        "imb_idx = np.concatenate([idx_neg, rng.choice(idx_pos, size=n_pos, replace=False)])",
        "y_imb = np.asarray(y_test)[imb_idx]; y_pred_imb = np.asarray(y_pred)[imb_idx]",
        "print(f'Class 1 prevalence in imbalanced test: {y_imb.mean():.2%}')",
        "",
        "# Naive baseline that always predicts 0",
        "from sklearn.metrics import accuracy_score",
        "print('Always-zero accuracy:', accuracy_score(y_imb, np.zeros_like(y_imb)))",
        "print('Real classifier accuracy:', accuracy_score(y_imb, y_pred_imb))",
        "print('\\nAlways-zero classification report:')",
        "print(classification_report(y_imb, np.zeros_like(y_imb), target_names=categories, zero_division=0))",
    ),
    md(
        "**Observation.** The trivial baseline reaches a high *accuracy* but its precision and recall on the positive class are zero. **Always inspect class-conditional metrics under imbalance.**",
    ),
    md("## 6. ROC and Precision-Recall curves"),
    code(
        "fpr, tpr, _ = roc_curve(y_test, y_score)",
        "roc_auc = auc(fpr, tpr)",
        "precision_curve, recall_curve, _ = precision_recall_curve(y_test, y_score)",
        "ap = average_precision_score(y_test, y_score)",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(11, 4))",
        "axes[0].plot(fpr, tpr, label=f'ROC (AUC={roc_auc:.3f})')",
        "axes[0].plot([0, 1], [0, 1], 'k--')",
        "axes[0].set_xlabel('False positive rate'); axes[0].set_ylabel('True positive rate')",
        "axes[0].set_title('ROC curve'); axes[0].legend()",
        "",
        "axes[1].plot(recall_curve, precision_curve, label=f'PR (AP={ap:.3f})')",
        "axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')",
        "axes[1].set_title('Precision-Recall curve'); axes[1].legend()",
        "plt.tight_layout(); plt.show()",
    ),
    md("## 7. Perplexity of a unigram and bigram language model"),
    code(
        "import math",
        "from collections import Counter",
        "",
        "# Tiny corpus",
        "train = 'the cat sat on the mat the cat ate the fish the dog ran on the floor'.split()",
        "test = 'the cat ran on the floor'.split()",
        "V = set(train); N_test = len(test)",
        "",
        "# Unigram model with add-1 smoothing",
        "uni = Counter(train); total = sum(uni.values())",
        "def P_uni(w):",
        "    return (uni[w] + 1) / (total + len(V))",
        "",
        "log_prob_uni = sum(math.log2(P_uni(w)) for w in test)",
        "ppl_uni = 2 ** (-log_prob_uni / N_test)",
        "print(f'Unigram perplexity on test: {ppl_uni:.3f}')",
        "",
        "# Bigram model with add-1 smoothing",
        "bigrams = Counter(zip(train, train[1:]))",
        "def P_bi(w_next, w_prev):",
        "    return (bigrams[(w_prev, w_next)] + 1) / (uni[w_prev] + len(V))",
        "",
        "log_prob_bi = math.log2(P_uni(test[0]))",
        "for prev, w in zip(test, test[1:]):",
        "    log_prob_bi += math.log2(P_bi(w, prev))",
        "ppl_bi = 2 ** (-log_prob_bi / N_test)",
        "print(f'Bigram perplexity on test:  {ppl_bi:.3f}')",
    ),
    md(
        "**Observation.** The bigram model typically achieves a lower perplexity than the unigram, because conditioning on the previous word improves prediction.",
    ),
    md("## 8. BLEU score"),
    code(
        "from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction",
        "",
        "reference = 'Tunisia won the African Cup of Nations'.split()",
        "candidates = [",
        "    'Tunisia won the cup'.split(),                       # very short",
        "    'Tunisia African the won Cup of Nations'.split(),    # right words, wrong order",
        "    'Tunisia won the African Cup of Nations'.split(),    # exact match",
        "]",
        "smoothing = SmoothingFunction().method1",
        "for c in candidates:",
        "    bleu = sentence_bleu([reference], c, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smoothing)",
        "    print(f'BLEU = {bleu:.3f}  for: {\" \".join(c)}')",
    ),
    md("## 9. ROUGE score"),
    code(
        "try:",
        "    from rouge_score import rouge_scorer",
        "    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)",
        "    for c in candidates:",
        "        scores = scorer.score(' '.join(reference), ' '.join(c))",
        "        print(f'\\nCandidate: {\" \".join(c)}')",
        "        for k, v in scores.items():",
        "            print(f'  {k}: P={v.precision:.3f}  R={v.recall:.3f}  F={v.fmeasure:.3f}')",
        "except ImportError:",
        "    print('Install rouge-score: pip install rouge-score')",
    ),
    md(
        "## Exercises",
        "",
        "**Exercise 1.** A NER tagger finds 80 true entities, misses 20, and produces 30 spurious entities. Compute Precision, Recall, F1 by hand and verify with `precision_recall_fscore_support`.",
        "",
        "**Exercise 2.** Build a fully imbalanced classification problem (e.g., 99% class 0). Train a real classifier and compare its F1 to that of a naive always-zero baseline. Plot the PR curve.",
        "",
        "**Exercise 3.** Implement Perplexity from scratch on a held-out passage of the Brown corpus, using the bigram model trained on the rest of the corpus.",
        "",
        "**Exercise 4.** Implement a simplified BLEU-1 (unigram precision + brevity penalty) without using NLTK. Verify on `reference = 'the cat is on the mat'` and `candidate = 'the cat sits on the mat'`.",
        "",
        "**Exercise 5 (synthesis).** Design an evaluation protocol for a Tunisian-Arabic dialect-to-French translation system. Identify which metrics you would report, which biases each carries (e.g., BLEU's surface sensitivity), and how you would complement them with human evaluation.",
    ),
]

# ---------------------------------------------------------------------------
# Build all 4 notebooks
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Building lab notebooks...")
    write("lab01-tokenization.ipynb", lab01)
    write("lab02-bow-tfidf-classifier.ipynb", lab02)
    write("lab03-word2vec-embeddings.ipynb", lab03)
    write("lab04-evaluation-metrics.ipynb", lab04)
    print("\nDone. Run `jupyter lab` to open them.")
